<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="W:\SpecSync\Samples\specsync-sample-plugins\nunit-test-source-plugin\SampleProject\NUnitTestProject\bin\Debug\net462\NUnitTestProject.dll" total="6" errors="0" failures="1" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2023-11-11" time="12:26:32">
  <environment nunit-version="2.6.2.12296" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 6.2.9200.0" platform="Win32NT" cwd="W:\SpecSync\Samples\specsync-sample-plugins\nunit-test-source-plugin\SampleProject\NUnitTestProject" machine-name="SPECSOL-D01" user="gaspar" user-domain="SPECSOL-D01" />
  <culture-info current-culture="en-US" current-uiculture="en-US" />
  <test-suite type="Assembly" name="W:\SpecSync\Samples\specsync-sample-plugins\nunit-test-source-plugin\SampleProject\NUnitTestProject\bin\Debug\net462\NUnitTestProject.dll" executed="True" result="Failure" success="False" time="0.158" asserts="0">
    <results>
      <test-suite type="Namespace" name="NUnitTestProject" executed="True" result="Failure" success="False" time="0.150" asserts="0">
        <results>
          <test-suite type="TestFixture" name="UnitTest1" executed="True" result="Failure" success="False" time="0.148" asserts="0">
            <results>
              <test-case name="NUnitTestProject.UnitTest1.OneFailingTest" executed="True" result="Failure" success="False" time="0.136" asserts="0">
                <categories>
                  <category name="tc:194" />
                </categories>
                <failure>
                  <message><![CDATA[This is a simulated error]]></message>
                  <stack-trace><![CDATA[at NUnitTestProject.UnitTest1.OneFailingTest()
]]></stack-trace>
                </failure>
              </test-case>
              <test-case name="NUnitTestProject.UnitTest1.OnePassingTest" executed="True" result="Success" success="True" time="0.000" asserts="0">
                <categories>
                  <category name="MyCategory" />
                  <category name="story:131" />
                  <category name="tc:193" />
                </categories>
              </test-case>
              <test-suite type="ParameterizedTest" name="SampleDataDriven" executed="True" result="Success" success="True" time="0.002" asserts="0">
                <categories>
                  <category name="tc:195" />
                </categories>
                <results>
                  <test-case name="NUnitTestProject.UnitTest1.SampleDataDriven(&quot;foo&quot;,1)" description="First" executed="True" result="Success" success="True" time="0.001" asserts="0" />
                  <test-case name="NUnitTestProject.UnitTest1.SampleDataDriven(&quot;bar&quot;,2)" description="Second" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                  <test-case name="NUnitTestProject.UnitTest1.SampleDataDriven(&quot;baz&quot;,3)" description="Third" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                </results>
              </test-suite>
            </results>
          </test-suite>
          <test-suite type="TestFixture" name="UnitTest2" executed="True" result="Success" success="True" time="0.000" asserts="0">
            <results>
              <test-case name="NUnitTestProject.UnitTest2.SomeOtherTest" executed="True" result="Success" success="True" time="0.000" asserts="0">
                <categories>
                  <category name="tc:196" />
                </categories>
              </test-case>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>